import React, { useState } from 'react';
import axios from 'axios';
import { 
    CreditCardIcon, 
    BanknotesIcon, 
    ArrowRightIcon,
    CheckCircleIcon,
    ExclamationCircleIcon,
    ArrowPathIcon
} from '@heroicons/react/24/solid';
import { useToast } from '../Components/Toast.jsx';

const TransactionSimulator = () => {
    const { addToast } = useToast();
    
    const [formData, setFormData] = useState({
        sender_account: '',
        receiver_account: '',
        amount: '',
        transaction_type: '',
        merchant_category: '',
        bank_id: 'SBI' // Default bank
    });
    
    const [loading, setLoading] = useState(false);
    const [message, setMessage] = useState('');
    const [error, setError] = useState('');
    const [success, setSuccess] = useState(false);
    const [federatedMessage, setFederatedMessage] = useState('');

    // Predefined options based on your ML model requirements
    const transactionTypes = [
        'transfer',
        'payment', 
        'withdrawal',
        'deposit',
        'purchase',
        'refund'
    ];

    const merchantCategories = [
        'grocery',
        'restaurant', 
        'gas_station',
        'retail',
        'healthcare',
        'entertainment',
        'travel',
        'education',
        'utilities',
        'online',
        'other'
    ];

    const banks = [
        'SBI',
        'HDFC', 
        'AXIS'
    ];

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value
        }));
        
        // Clear messages when user starts typing
        if (message || error || federatedMessage) {
            setMessage('');
            setError('');
            setSuccess(false);
            setFederatedMessage('');
        }
    };

    const validateForm = () => {
        const { sender_account, receiver_account, amount, transaction_type, merchant_category } = formData;
        
        if (!sender_account.trim()) return 'Sender account is required';
        if (!receiver_account.trim()) return 'Receiver account is required';
        if (!amount || isNaN(amount) || parseFloat(amount) <= 0) return 'Valid amount is required';
        if (!transaction_type) return 'Transaction type is required';
        if (!merchant_category) return 'Merchant category is required';
        if (sender_account === receiver_account) return 'Sender and receiver accounts must be different';
        
        return null;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        
        // Validate form
        const validationError = validateForm();
        if (validationError) {
            setError(validationError);
            return;
        }

        setLoading(true);
        setError('');
        setMessage('');
        
        try {
            // Prepare transaction data for backend/ML processing
            const transactionData = {
                // User input fields
                sender_account: formData.sender_account.trim(),
                receiver_account: formData.receiver_account.trim(), 
                amount: parseFloat(formData.amount),
                transaction_type: formData.transaction_type,
                merchant_category: formData.merchant_category,
                bank_id: formData.bank_id,
                
                // These will be auto-generated by backend
                // But we define the structure for ML compatibility
                metadata: {
                    // Auto-generated fields that backend should populate:
                    // timestamp: new Date(),
                    // transaction_id: generated_uuid,
                    // ip_address: client_ip,
                    // device_hash: generated_hash,
                    // location_lat: generated_or_detected,
                    // location_long: generated_or_detected,
                    // time_since_last_transaction: calculated,
                    // spending_deviation_score: calculated,
                    // velocity_score: calculated, 
                    // geo_anomaly_score: calculated,
                    // user_id: from_session,
                    // merchant_id: generated,
                    // account_age_days: calculated,
                    // transaction_hour: from_timestamp,
                    // day_of_week: from_timestamp,
                    // is_weekend: calculated,
                    // num_transactions_today: calculated,
                    // avg_transaction_amount: calculated,
                    // processed_for_fl: false,
                    // is_fraud: to_be_predicted
                }
            };

            const response = await axios.post('http://localhost:5000/api/simulate-transaction', transactionData);
            
            setSuccess(true);
            setMessage(`Transaction simulated successfully! Transaction ID: ${response.data.transactionId}`);
            
            // INSTANT MESSAGE: Sufficient Data Gathered
            setFederatedMessage('Sufficient Data Gathered, Trigger Federated Model Updates');
            
            // TOAST AFTER 2 SECONDS: Model Update Complete
            setTimeout(() => {
                addToast('MODEL UPDATE COMPLETE', 'success', 4000);
            }, 2000);
            
            // Reset form after successful submission
            setTimeout(() => {
                setFormData({
                    sender_account: '',
                    receiver_account: '',
                    amount: '',
                    transaction_type: '',
                    merchant_category: '',
                    bank_id: 'SBI'
                });
                setSuccess(false);
                setMessage('');
                setFederatedMessage('');
            }, 6000); // Extended timeout to show federated message longer
            
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to simulate transaction. Please try again.');
            console.error('Transaction simulation error:', err);
        } finally {
            setLoading(false);
        }
    };

    const resetForm = () => {
        setFormData({
            sender_account: '',
            receiver_account: '',
            amount: '',
            transaction_type: '',
            merchant_category: '',
            bank_id: 'SBI'
        });
        setMessage('');
        setError('');
        setSuccess(false);
        setFederatedMessage('');
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
            <div className="max-w-2xl mx-auto">
                {/* Header */}
                <div className="text-center mb-8">
                    <div className="flex items-center justify-center mb-4">
                        <BanknotesIcon className="h-12 w-12 text-blue-600 mr-3" />
                        <h1 className="text-3xl font-bold text-gray-800">Transaction Simulator</h1>
                    </div>
                    <p className="text-gray-600">Simulate banking transactions for testing and analysis</p>
                </div>

                {/* Main Form Card */}
                <div className="bg-white rounded-2xl shadow-xl p-8 border border-gray-200">
                    <form onSubmit={handleSubmit} className="space-y-6">
                        {/* Bank Selection */}
                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-2">
                                Bank
                            </label>
                            <select
                                name="bank_id"
                                value={formData.bank_id}
                                onChange={handleInputChange}
                                className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                            >
                                {banks.map(bank => (
                                    <option key={bank} value={bank}>{bank} Bank</option>
                                ))}
                            </select>
                        </div>

                        {/* Account Information */}
                        <div className="grid md:grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">
                                    Sender Account *
                                </label>
                                <div className="relative">
                                    <CreditCardIcon className="absolute left-3 top-3 h-6 w-6 text-gray-400" />
                                    <input
                                        type="text"
                                        name="sender_account"
                                        value={formData.sender_account}
                                        onChange={handleInputChange}
                                        placeholder="Enter sender account number"
                                        className="w-full pl-11 pr-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                                        required
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">
                                    Receiver Account *
                                </label>
                                <div className="relative">
                                    <CreditCardIcon className="absolute left-3 top-3 h-6 w-6 text-gray-400" />
                                    <input
                                        type="text"
                                        name="receiver_account"
                                        value={formData.receiver_account}
                                        onChange={handleInputChange}
                                        placeholder="Enter receiver account number"
                                        className="w-full pl-11 pr-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                                        required
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Amount */}
                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-2">
                                Amount *
                            </label>
                            <div className="relative">
                                <span className="absolute left-3 top-3 text-gray-500 font-semibold">$</span>
                                <input
                                    type="number"
                                    name="amount"
                                    value={formData.amount}
                                    onChange={handleInputChange}
                                    placeholder="0.00"
                                    min="0.01"
                                    step="0.01"
                                    className="w-full pl-8 pr-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                                    required
                                />
                            </div>
                        </div>

                        {/* Transaction Details */}
                        <div className="grid md:grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">
                                    Transaction Type *
                                </label>
                                <select
                                    name="transaction_type"
                                    value={formData.transaction_type}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                                    required
                                >
                                    <option value="">Select transaction type</option>
                                    {transactionTypes.map(type => (
                                        <option key={type} value={type}>
                                            {type.charAt(0).toUpperCase() + type.slice(1).replace('_', ' ')}
                                        </option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">
                                    Merchant Category *
                                </label>
                                <select
                                    name="merchant_category"
                                    value={formData.merchant_category}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-200"
                                    required
                                >
                                    <option value="">Select merchant category</option>
                                    {merchantCategories.map(category => (
                                        <option key={category} value={category}>
                                            {category.charAt(0).toUpperCase() + category.slice(1).replace('_', ' ')}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex gap-4 pt-4">
                            <button
                                type="submit"
                                disabled={loading}
                                className={`flex-1 flex items-center justify-center py-3 px-6 rounded-lg font-semibold text-white transition duration-200 ${
                                    loading
                                        ? 'bg-gray-400 cursor-not-allowed'
                                        : success 
                                        ? 'bg-green-600 hover:bg-green-700'
                                        : 'bg-blue-600 hover:bg-blue-700'
                                }`}
                            >
                                {loading ? (
                                    <>
                                        <ArrowPathIcon className="animate-spin h-5 w-5 mr-2" />
                                        Simulating...
                                    </>
                                ) : success ? (
                                    <>
                                        <CheckCircleIcon className="h-5 w-5 mr-2" />
                                        Success!
                                    </>
                                ) : (
                                    <>
                                        <ArrowRightIcon className="h-5 w-5 mr-2" />
                                        Simulate Transaction
                                    </>
                                )}
                            </button>

                            <button
                                type="button"
                                onClick={resetForm}
                                className="px-6 py-3 border border-gray-300 rounded-lg font-semibold text-gray-700 hover:bg-gray-50 transition duration-200"
                            >
                                Reset
                            </button>
                        </div>
                    </form>

                    {/* Status Messages */}
                    {message && (
                        <div className="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg flex items-center">
                            <CheckCircleIcon className="h-5 w-5 text-green-600 mr-2 flex-shrink-0" />
                            <p className="text-green-700">{message}</p>
                        </div>
                    )}

                    {error && (
                        <div className="mt-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-center">
                            <ExclamationCircleIcon className="h-5 w-5 text-red-600 mr-2 flex-shrink-0" />
                            <p className="text-red-700">{error}</p>
                        </div>
                    )}

                    {/* Federated Learning Message */}
                    {federatedMessage && (
                        <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg flex items-center animate-pulse shadow-sm">
                            <div className="h-5 w-5 text-blue-600 mr-2 flex-shrink-0">
                                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                                </svg>
                            </div>
                            <p className="text-blue-700 font-semibold tracking-wide">{federatedMessage}</p>
                            <div className="ml-auto">
                                <div className="flex space-x-1">
                                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce"></div>
                                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{animationDelay: '0.1s'}}></div>
                                    <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{animationDelay: '0.2s'}}></div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Info Card */}
                <div className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-6">
                    <h3 className="text-lg font-semibold text-blue-800 mb-2">How it works</h3>
                    <div className="text-blue-700 text-sm space-y-2">
                        <p>• Fill in the required transaction details above</p>
                        <p>• Additional fields (timestamps, location, user data) are auto-generated</p>
                        <p>• The transaction is processed through our fraud detection ML model</p>
                        <p>• Results are stored in the database for analysis and federated learning</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TransactionSimulator;
